# -*- coding: utf-8 -*-
"""Dichromatic_Polynomial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14nV0LdhiPNEo4cqc7lRZ_8sS2PQT-PjX

# Dichromatic Polynomial of a Digraph

Implementation of the recursive formula from **Theorem 2** of:

> González-Moreno et al., *The Dichromatic Polynomial of a Digraph*,  
> Graphs and Combinatorics 38 (2022), article 85.

Input format: Collapse section CODE (click on the little arrow to the left of it) and go to section "TO USE" to view the 3 different input formats.

---
**Run all cells top to bottom before using anything.**

# CODE

## Cell 1 — Imports
"""

from sympy import symbols, Poly
from itertools import combinations
import matplotlib.pyplot as plt
import numpy as np

k = symbols('k')
print("✓ imports ok")

"""## Cell 2 — digraph6 Codec"""

def _n_from_bytes(data, pos):
    if data[pos] != 126:
        return data[pos] - 63, pos + 1
    pos += 1
    if data[pos] != 126:
        x = 0
        for _ in range(3):
            x = (x << 6) | (data[pos] - 63); pos += 1
        return x, pos
    pos += 1
    x = 0
    for _ in range(6):
        x = (x << 6) | (data[pos] - 63); pos += 1
    return x, pos

def parse_d6(s):
    """digraph6 string → n×n adjacency matrix."""
    s = s.strip()
    if s.startswith(">>digraph6<<"): s = s[len(">>digraph6<<"):]
    if s.startswith("&"): s = s[1:]
    data = s.encode("ascii")
    n, pos = _n_from_bytes(data, 0)
    bits = []
    for byte in data[pos:]:
        v = byte - 63
        for shift in range(5, -1, -1):
            bits.append((v >> shift) & 1)
    adj = [[0]*n for _ in range(n)]
    idx = 0
    for i in range(n):
        for j in range(n):
            if idx < len(bits):
                adj[i][j] = bits[idx]; idx += 1
    return adj

def to_d6(adj):
    """n×n adjacency matrix → digraph6 string."""
    n = len(adj)
    if n <= 62:
        n_bytes = bytes([n + 63])
    elif n <= 258047:
        x = n; b = []
        for _ in range(3): b.append((x & 0x3F) + 63); x >>= 6
        n_bytes = bytes([126]) + bytes(reversed(b))
    else:
        x = n; b = []
        for _ in range(6): b.append((x & 0x3F) + 63); x >>= 6
        n_bytes = bytes([126, 126]) + bytes(reversed(b))
    bits = [adj[i][j] for i in range(n) for j in range(n)]
    while len(bits) % 6: bits.append(0)
    r_bytes = []
    for i in range(0, len(bits), 6):
        v = 0
        for b in bits[i:i+6]: v = (v << 1) | b
        r_bytes.append(v + 63)
    return "&" + (n_bytes + bytes(r_bytes)).decode("ascii")

print("✓ digraph6 codec ok")

"""## Cell 3 — Graph Utilities"""

def _n(adj): return len(adj)
def _adj_copy(adj): return [row[:] for row in adj]

def _is_acyclic(adj):
    """DFS cycle detection. Returns True if no directed cycle."""
    n = _n(adj)
    WHITE, GRAY, BLACK = 0, 1, 2
    color = [WHITE] * n
    def dfs(u):
        color[u] = GRAY
        for v in range(n):
            if adj[u][v]:
                if color[v] == GRAY: return True
                if color[v] == WHITE and dfs(v): return True
        color[u] = BLACK
        return False
    return not any(dfs(u) for u in range(n) if color[u] == 0)

def _strong_components(adj):
    """Kosaraju's algorithm → list of frozensets."""
    n = _n(adj)
    visited = [False]*n; order = []
    def dfs1(u):
        stack = [(u, 0)]
        while stack:
            v, idx = stack[-1]
            if idx == 0: visited[v] = True
            found = False
            for w in range(idx, n):
                stack[-1] = (v, w+1)
                if adj[v][w] and not visited[w]:
                    visited[w] = True; stack.append((w, 0)); found = True; break
            if not found: stack.pop(); order.append(v)
    for u in range(n):
        if not visited[u]: dfs1(u)
    T = [[adj[j][i] for j in range(n)] for i in range(n)]
    visited2 = [False]*n; comps = []
    def dfs2(u):
        comp = []; stack = [u]; visited2[u] = True
        while stack:
            v = stack.pop(); comp.append(v)
            for w in range(n):
                if T[v][w] and not visited2[w]:
                    visited2[w] = True; stack.append(w)
        return comp
    for u in reversed(order):
        if not visited2[u]: comps.append(frozenset(dfs2(u)))
    return comps

print("✓ graph utilities ok")

"""## Cell 4 — Digraph Operations"""

def _add_arc(adj, u, v):
    a = _adj_copy(adj); a[u][v] = 1; return a

def _contract(adj, vertex_set):
    """Contract a set of vertices into one (no loops, no parallel arcs)."""
    n = _n(adj); S = set(vertex_set)
    others = sorted(set(range(n)) - S)
    new_order = [min(S)] + others
    m = 1 + len(others)
    new_adj = [[0]*m for _ in range(m)]
    for i, u in enumerate(new_order):
        for j, v in enumerate(new_order):
            if i == j: continue
            u_group = S if i == 0 else {u}
            v_group = S if j == 0 else {v}
            new_adj[i][j] = 1 if any(adj[a][b] for a in u_group for b in v_group) else 0
    return new_adj

def _find_non_symmetric_pair(adj):
    """Find (u,v) where NOT both u->v and v->u. Returns None if fully symmetric."""
    n = _n(adj)
    for u in range(n):
        for v in range(u+1, n):
            if not (adj[u][v] and adj[v][u]): return u, v
    return None

def _paths_of_length_ge2(adj, u, v):
    """Simple (u,v)-paths of length >= 2 whose induced subdigraph is acyclic."""
    n = _n(adj); results = []
    def dfs(current, path, visited):
        for nxt in range(n):
            if not adj[current][nxt]: continue
            if nxt == v and len(path) >= 2:
                full = path + [v]
                induced = [[adj[a][b] for b in full] for a in full]
                if _is_acyclic(induced): results.append(tuple(full))
            elif nxt != v and nxt not in visited:
                visited.add(nxt); dfs(nxt, path+[nxt], visited); visited.remove(nxt)
    dfs(u, [u], {u})
    return results

def _build_equivalence_classes(paths, u, v):
    """
    Equivalence classes of Huv under relation (3) of the paper:
    H_i ~ H_j iff union V(T) for T in H_i = union V(T) for T in H_j.
    Returns list of distinct R*_i vertex-sets (frozensets).
    """
    if not paths: return []
    m = len(paths)
    seen = {}
    for r in range(1, m+1):
        for combo in combinations(range(m), r):
            vset = frozenset(vtx for idx in combo for vtx in paths[idx])
            if vset not in seen: seen[vset] = combo
    return list(seen.keys())

print("✓ digraph operations ok")

"""## Cell 5 — Dichromatic Polynomial (Theorem 2)

$$P(D,k) = P(D + \{uv,vu\},\,k) + P(D/\{u,v\},\,k) + \sum_{i=1}^{\ell} P(D/R_i^*,\,k)$$

**Bug fix included:** R\*ᵢ terms where the induced subgraph has a cycle contribute 0
(coloring all those vertices the same would create a monochromatic cycle → invalid).

"""

def _poly_complete_symmetric(n):
    """P(complete symmetric digraph) = k(k-1)···(k-n+1)."""
    result = Poly(1, k, domain='ZZ')
    for i in range(n): result = result * Poly(k - i, k, domain='ZZ')
    return result

def _rec(adj):
    n = _n(adj)
    if n <= 1:                    return Poly(k**n, k, domain='ZZ')
    if _is_acyclic(adj):          return Poly(k**n, k, domain='ZZ')

    # Decompose by strong components (Theorem 5)
    comps = _strong_components(adj)
    if len(comps) > 1:
        result = Poly(1, k, domain='ZZ')
        for comp in comps:
            comp = sorted(comp)
            sub = [[adj[u][v] for v in comp] for u in comp]
            result = result * _rec(sub)
        return result

    pair = _find_non_symmetric_pair(adj)
    if pair is None: return _poly_complete_symmetric(n)  # fully symmetric

    u, v = pair

    # Term 1: make (u,v) symmetric
    p1 = _rec(_add_arc(_add_arc(adj, u, v), v, u))

    # Term 2: contract {u,v}
    p2 = _rec(_contract(adj, {u, v}))

    # Terms 3+: one per equivalence class R*_i
    all_paths = _paths_of_length_ge2(adj, u, v) + _paths_of_length_ge2(adj, v, u)
    R_stars   = _build_equivalence_classes(all_paths, u, v)

    p3 = Poly(0, k, domain='ZZ')
    for R_star in R_stars:
        # Skip if induced subgraph on R*_i has a cycle:
        # coloring all those vertices the same would create a monochromatic cycle.
        R_list  = sorted(R_star)
        induced = [[adj[a][b] for b in R_list] for a in R_list]
        if not _is_acyclic(induced):
            continue
        p3 = p3 + _rec(_contract(adj, R_star))

    return p1 + p2 + p3

def dichromatic_poly(adj):
    """Return P(D, k) as a sympy Poly."""
    return _rec(adj)

def dichromatic_number(adj):
    """Return dc(D) = min{ k ∈ ℤ⁺ : P(D,k) > 0 }."""
    if _is_acyclic(adj): return 1
    poly = dichromatic_poly(adj)
    for kv in range(1, _n(adj) + 2):
        if poly.eval(kv) > 0: return kv
    return _n(adj)

print("✓ dichromatic_poly and dichromatic_number ok")

"""## Cell 6 — I/O Helpers"""

def process_d6_string(s):
    """Parse one digraph6 string and print polynomial + dichromatic number."""
    s = s.strip()
    if not s or s.startswith("#"): return
    adj  = parse_d6(s)
    poly = dichromatic_poly(adj)
    dc   = dichromatic_number(adj)
    print(f"d6     : {s}")
    print(f"n      : {_n(adj)}")
    print(f"P(D,k) : {poly.as_expr()}")
    print(f"dc(D)  : {dc}")
    print()

def process_d6_file(path):
    """Process every graph in a .d6 file."""
    with open(path) as fh:
        for line in fh:
            process_d6_string(line)

print("✓ I/O helpers ok")

"""## Cell 6b — Tournament Format (McKay upper-triangle)"""

import math

def _n_from_tri_len(L):
    """Infer n from upper-triangle bit string of length L = n*(n-1)/2."""
    n = int((1 + math.sqrt(1 + 8*L)) / 2)
    assert n*(n-1)//2 == L, f"String length {L} is not a valid upper-triangle length"
    return n

def parse_tournament(s):
    s = s.strip()
    n = _n_from_tri_len(len(s))
    adj = [[0]*n for _ in range(n)]
    idx = 0

    for i in range(n):
        for j in range(i+1, n):
            if s[idx] == '1':
                adj[i][j] = 1
            else:
                adj[j][i] = 1
            idx += 1

    return adj

def process_tournament_string(s):
    """Parse one tournament string and print polynomial + dichromatic number."""
    s = s.strip()
    if not s or s.startswith("#"): return
    adj  = parse_tournament(s)
    poly = dichromatic_poly(adj)
    dc   = dichromatic_number(adj)
    print(f"tournament : {s}")
    print(f"  n      = {_n(adj)}")
    print(f"  P(D,k) = {poly.as_expr()}")
    print(f"  dc(D)  = {dc}")
    print()

def process_tournament_file(path):
    """Process every tournament in a file (one upper-triangle string per line)."""
    with open(path) as fh:
        for line in fh:
            process_tournament_string(line)

print("✓ tournament format loaded")

# ── Process a whole tournament file ──────────────────────────────────────────
# Uncomment and point to your file:
# process_tournament_file("tournaments5.txt") # change name to local file

"""## Graph printing"""

def print_graph(adj, labels=None):
    """Print a text representation of the digraph."""
    n = len(adj)
    if labels is None:
        labels = [str(i) for i in range(n)]
    print("Digraph:")
    for i in range(n):
        arcs = [labels[j] for j in range(n) if adj[i][j]]
        if arcs:
            print(f"  {labels[i]} → {', '.join(arcs)}")
        else:
            print(f"  {labels[i]} → (none)")

def draw_graph(adj, labels=None, title="Digraph"):
    """Draw the digraph with a circular layout."""
    n = len(adj)
    if labels is None:
        labels = [str(i) for i in range(n)]

    angles = [2 * np.pi * i / n for i in range(n)]
    pos = {i: (np.cos(a), np.sin(a)) for i, a in enumerate(angles)}

    fig, ax = plt.subplots(figsize=(5, 5))
    ax.set_aspect('equal')
    ax.axis('off')
    ax.set_title(title, fontsize=13)

    for i in range(n):
        for j in range(n):
            if not adj[i][j]: continue
            xi, yi = pos[i]
            xj, yj = pos[j]
            if adj[j][i]:  # offset symmetric arcs
                dx, dy = yj - yi, -(xj - xi)
                norm = np.sqrt(dx**2 + dy**2) + 1e-9
                off = 0.08
                xi2 = xi + off*dx/norm; yi2 = yi + off*dy/norm
                xj2 = xj + off*dx/norm; yj2 = yj + off*dy/norm
            else:
                xi2, yi2, xj2, yj2 = xi, yi, xj, yj
            ax.annotate("",
                xy=(xj2, yj2), xytext=(xi2, yi2),
                arrowprops=dict(arrowstyle="-|>", color="steelblue",
                                lw=1.5, mutation_scale=15,
                                shrinkA=14, shrinkB=14))

    for i in range(n):
        x, y = pos[i]
        ax.add_patch(plt.Circle((x, y), 0.1, color='steelblue', zorder=3))
        ax.text(x, y, labels[i], ha='center', va='center',
                color='white', fontsize=11, fontweight='bold', zorder=4)

    ax.set_xlim(-1.4, 1.4); ax.set_ylim(-1.4, 1.4)
    plt.tight_layout()
    plt.show()

"""---
## Cell 7 — TEST CASES

Edit and re-run any of the cells below.

"""

# 4-cycle 0->1->2->3->0 plus arcs 0->4
# In the paper: Proof 8, case 2b, P(C*,k): P(D,k) = k^5 - k^2
adj = [
    [0, 1, 0, 0, 1],   # 0 -> 1, 4
    [0, 0, 1, 0, 0],   # 1 -> 2
    [0, 0, 0, 1, 0],   # 2 -> 3
    [1, 0, 0, 0, 0],   # 3 -> 0
    [0, 0, 0, 0, 0],   # 4 -> 2
]
print("d6    :", to_d6(adj))
print("P(D,k):", dichromatic_poly(adj).as_expr())
print("dc(D) :", dichromatic_number(adj))

# 4-cycle 0->1->2->3->0 plus arcs 0->4 and 4->2
# In the paper: Proof 8, case 2b, P(C**,k): P(D,k) = k^5 - 2k^2 + k
adj = [
    [0, 1, 0, 0, 1],   # 0 -> 1, 4
    [0, 0, 1, 0, 0],   # 1 -> 2
    [0, 0, 0, 1, 0],   # 2 -> 3
    [1, 0, 0, 0, 0],   # 3 -> 0
    [0, 0, 1, 0, 0],   # 4 -> 2
]
print("d6    :", to_d6(adj))
print("P(D,k):", dichromatic_poly(adj).as_expr())
print("dc(D) :", dichromatic_number(adj))

# 4 - cycle 1->2->3->4 and 3-cycle 1->2->0->1
# see Proof 8, case 3 (before a); I believe that there is a typo in the book, see handwritten notes; should be k^5 - k^3 - k^2 +k
adj_c4_c3 = [
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0]
    ]
print("D")
print("P(D,k):", dichromatic_poly(adj_c4_c3).as_expr())
print("dc(D) :", dichromatic_number(adj_c4_c3))

# Same as above with the added edge 0->3; should yield same polynomial
adj_c4_c3 = [
    [0, 1, 0, 0, 1],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0]
    ]
print("D")
print("P(D,k):", dichromatic_poly(adj_c4_c3).as_expr())
print("dc(D) :", dichromatic_number(adj_c4_c3))

# STILL WORKING ON THIS
adj_c4_c3 = [
    [0, 1, 0, 1, 0],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [1, 1, 0, 0, 0]
    ]
print("D")
print("P(D,k):", dichromatic_poly(adj_c4_c3).as_expr())
print("dc(D) :", dichromatic_number(adj_c4_c3))

# ── D: process a whole .d6 file ──────────────────────────────────────────────
# Uncomment and point to your file:
# process_d6_file("digraphs4.d6")

adj = [[0,1,0],[0,0,1],[1,0,0]]   # C3

print_graph(adj)
print(f"P(D,k) = {dichromatic_poly(adj).as_expr()},  dc = {dichromatic_number(adj)}")
draw_graph(adj, title=f"P = {dichromatic_poly(adj).as_expr()}")

"""# TO USE: Obtaining Dichromatic Polynomial

### Option 1:
You can pass the input in matrix form. Enter a matrix for your graph; entries are binary numbers. Entry M[ij] = 1 means that there exists a vertex from i to j. M[ij] = 0 means that there does not exist a vertex from i to j. E.g. C3 would have a matrix of
$\begin{bmatrix} 0 & 1 & 0 \\
0 & 0 & 1 \\
1 & 0 & 0 \end{bmatrix}$
corresponding to the edges $0 \to 1, 1 \to 2, 2 \to 0$.
"""

# for processing & calculating dichromatic number & polynomial
edge_matrix = [
    [0, 1, 0, 1, 1],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0],
    [0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0]
    ]
print("D")
print("P(D,k):", dichromatic_poly(edge_matrix).as_expr())
print("dc(D) :", dichromatic_number(edge_matrix))

# for printing
print_graph(edge_matrix)
draw_graph(edge_matrix, title=f"P = {dichromatic_poly(edge_matrix).as_expr()}")

"""### Option 2:
You can pass the input in digraph6 form from https://users.cecs.anu.edu.au/~bdm/data/digraphs.html. This includes sections
- Digraphs
- Oriented graphs
- Eulerian graphs
- Vertex-transitive tournaments and
- Non-reconstructable digraphs
(all with or without loops).
"""

# for processing the string & calculating dichromatic number & polynomial
process_d6_string("&B[O")

# for printing the graph
mat = parse_d6("&EIC`OHa")
print_graph(mat)
draw_graph(mat, title=f"P = {dichromatic_poly(mat).as_expr()}")

"""### Option 3:
You can pass the input in upper triangle form of the adjacency matrix in row order form from https://users.cecs.anu.edu.au/~bdm/data/digraphs.html. This includes sections
- Tournaments
- Self-converse-Tournaments
- Regular and Semi-regular Tournaments
- Locally-transitive Tournaments
- Acyclic Digraphs.


Uncomment and run the cell below to use this input format. You can read more about the encoding in the matrices in the above link.
"""

# for processing the string & calculating dichromatic number & polynomial
upper_triang = parse_tournament('011000')
print("D")
print("P(D,k):", dichromatic_poly(upper_triang).as_expr())
print("dc(D) :", dichromatic_number(upper_triang))

# for printing
print_graph(upper_triang)
draw_graph(upper_triang, title=f"P = {dichromatic_poly(upper_triang).as_expr()}")

"""### counting k-cycles"""

"""
Count and enumerate directed k-cycles in a directed graph given its adjacency matrix.

A directed k-cycle is a sequence of k DISTINCT vertices v0 -> v1 -> ... -> v(k-1) -> v0
following directed edges. Each cycle is counted once: rotations of the same cycle
(e.g. (0,1,2) and (1,2,0) and (2,0,1)) are the same cycle, so we canonicalize by
always starting the walk at its smallest-index vertex.

Note: a directed cycle and its reverse (e.g. 0->1->2->0 vs 0->2->1->0) are different
cycles unless both directions of edges happen to exist -- they are counted separately,
since the graph is directed.
"""

def find_k_cycles(adj, k):
    """
    adj: n x n list of lists (0/1), adj[i][j] = 1 means edge i -> j
    k:   cycle length (number of distinct vertices in the cycle), k >= 1

    Returns a list of cycles, each cycle given as a tuple of vertex indices
    (v0, v1, ..., v(k-1)) meaning v0->v1->...->v(k-1)->v0, with v0 = min(cycle).
    """
    n = len(adj)
    if k < 1 or k > n:
        return []

    cycles = []

    def dfs(start, current, visited, path):
        if len(path) == k:
            if adj[current][start]:
                cycles.append(tuple(path))
            return
        for nxt in range(n):
            # nxt >= start keeps 'start' as the minimum vertex in the cycle,
            # which is what canonicalizes away rotations
            if adj[current][nxt] and nxt not in visited and nxt >= start:
                visited.add(nxt)
                path.append(nxt)
                dfs(start, nxt, visited, path)
                path.pop()
                visited.remove(nxt)

    for s in range(n):
        dfs(s, s, {s}, [s])

    return cycles


def parse_adjacency(s):
    """Parse rows like '010,001,100' into a 0/1 adjacency matrix."""
    rows = [r.strip() for r in s.strip().split(',')]
    n = len(rows)
    adj = []
    for r in rows:
        row = [int(ch) for ch in r]
        if len(row) != n or any(v not in (0, 1) for v in row):
            raise ValueError(f"Invalid row '{r}': must be {n} characters of 0/1")
        adj.append(row)
    return adj


def format_cycle(cycle):
    return " -> ".join(str(v) for v in cycle) + f" -> {cycle[0]}"


def main():
    print("Enter the adjacency matrix as rows of 0/1 separated by commas.")
    print("Example for a 3-vertex graph with edges 0->1, 1->2, 2->0:  010,001,100")
    s = input("Adjacency matrix: ").strip()
    adj = parse_adjacency(s)
    n = len(adj)
    print(f"Parsed a {n}x{n} adjacency matrix.")

    k = int(input("Cycle length k: ").strip())

    cycles = find_k_cycles(adj, k)
    #print(f"\nNumber of directed {k}-cycles: {len(cycles)}")
    #if cycles:
        #print("Cycles (vertices 0-indexed):")
        #for c in cycles:
            #print("  " + format_cycle(c))